### PR TITLE
Fixes for type gen

### PR DESCRIPTION
**Pull request by deadlinecode**

### CODE REVIEW

**Comment by deadlinecode** [comment]
Looks like eden treaty is working kinda
I still need to fix the prepended "index" stuff for "/" routes

**Comment by deadlinecode** [comment]
@kravetsone looks like eden fetch & treaty are working now :3
You can review and test if you want and then it should me ready to merge :0

**Comment by deadlinecode** [comment]
Oh yeah right
This fixes #16

**Comment by kravetsone** [comment]
> @kravetsone looks like eden fetch & treaty are working now :3
> You can review and test if you want and then it should me ready to merge :0

Thanks for you work!
If you need as soon as possible i can publish it now)

**Comment by deadlinecode** [comment]
Yeah would be great im currently working on something so wouldn't be that bad if you bould make a minor release :3

**Comment by kravetsone** [comment]
> Yeah would be great im currently working on something so wouldn't be that bad if you bould make a minor release :3

You test it well?)
but I think it doesn't matter if something doesn't work as it should (because before that it broke at all)

**Comment by deadlinecode** [comment]
I tested it as well as i could xD
But it should definetly work better than before xD

**Comment by kravetsone** [comment]
> I tested it as well as i could xD
> But it should definetly work better than before xD

https://github.com/kravetsone/elysia-autoload/actions/runs/10435545522/job/28899634313#step:7:1

CICD failed

**Comment by kravetsone** [comment]
> > I tested it as well as i could xD
> > But it should definetly work better than before xD
> 
> https://github.com/kravetsone/elysia-autoload/actions/runs/10435545522/job/28899634313#step:7:1
> 
> CICD failed

@deadlinecode

**Pull request merged**
