### PR TITLE
feat: add NodeJS version

### PR DESCRIPTION
**Pull request by rtritto**
Create a NodeJS version, so it can be used with https://github.com/elysiajs/node-adapter

### Differences
- use `fs.globSync` (it's introduced with NodeJS 22.0.0) instead of `Bun.glob`
- use `fs.writeFileSync` instead `Bun.write`

### Notes:
- `@types/node` is added as dev dependency because globSync (Node v22) isn't recognized.
  `@types/bun` include `@types/node` but is v20 (and not >=v22).
  After https://github.com/oven-sh/bun/pull/13987 is merged, `@types/node` dev dependency can be removed.

### TODO
- [x] test build
- [x] `.ts/.tsx` files needs to be transpiled

Fix #30

### CODE REVIEW

**Comment by kravetsone** [comment]
Why not typeof bun === "undefined"

**Comment by kravetsone** [comment]
Also we should check that esbuild plugin not broken with it

**Comment by rtritto** [comment]
> Why not typeof bun === "undefined"

Done, thanks!

**Comment by rtritto** [comment]
> Also we should check that esbuild plugin not broken with it

I tested:
- with Vite/Vike (`esbuild` in the hood):
  - With Node, using `@elysia/node`, on https://github.com/kravetsone/elysia-autoload/blob/5920060b5ba819977b48e195fc526f4c331bb201/src/index.ts#L137 I get:
    ```console
    Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    ```
    
    We should change:
    ```diff
    - const file = await import(fullPath);
    + import { pathToFileURL } from 'node:url'
    + const fileURL = pathToFileURL(fullPath);
    + const file = await import(fileURL.href);
    ```
    Should we do this change in this PR?
  
  - With Bun, I have no issue
- without Vite/Vike, I have no issues

**Comment by rtritto** [comment]
I added `@types/node` dev dependency because `globSync` (Node v22) isn't recognized.
`@types/bun` also include `@types/node` but is v20 (Node v20).
After https://github.com/oven-sh/bun/pull/13987 is merged, `@types/node` dev dependency can be removed.

**Comment by kravetsone** [comment]
> > Also we should check that esbuild plugin not broken with it
> 
> I tested on Windows side:
> 
> * with Vite/Vike (`esbuild` in the hood):
>   
>   * with Node, using `@elysia/node`, I get:
>     ```
>     Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
>     ```
>     
>     
>         
>           
>         
>     
>           
>         
>     
>         
>       
>     We should change:
>     https://github.com/kravetsone/elysia-autoload/blob/5920060b5ba819977b48e195fc526f4c331bb201/src/index.ts#L137
>     
>     ```diff
>     - const file = await import(fullPath);
>     + import { pathToFileURL } from 'node:url'
>     + const fileURL = pathToFileURL(fullPath);
>     + const file = await import(fileURL.href);
>     ```
>     
>     
>         
>           
>         
>     
>           
>         
>     
>         
>       
>     Should we do the change in this PR?
>   * with Bun, I have no issue
> * without Vite/Vike, I have no issues:
>   
>   * with Node + `@elysia/node`
>   * with Bun

based i see this issue in my https://github.com/gramiojs/autoload too

Bun just works fine

**Comment by kravetsone** [comment]
> Also we should check that esbuild plugin not broken with it

did u try it?
https://github.com/kravetsone/esbuild-plugin-autoload

But for now it uses `Bun.Glob` api (only in `Bun.build` step)

**Comment by rtritto** [comment]
> > Also we should check that esbuild plugin not broken with it
> 
> did u try it? https://github.com/kravetsone/esbuild-plugin-autoload
> 
> But for now it uses `Bun.Glob` api (only in `Bun.build` step)

No, I will try

**Comment by rtritto** [comment]
How can we test with `esbuild`?

It that https://github.com/kravetsone/esbuild-plugin-autoload?tab=readme-ov-file#esbuild-usage the correct reference?

Draft:
```ts
await esbuild
  .build({
    target: "bun",
    outdir: "out",
    plugins: [{
      name: 'elysia-autoload',
      setup: autoload
    }]
  })
  .then(console.log)
```

**Comment by rtritto** [comment]
Changed to use glob with async iteration with streams.
If needed, `sortByNestedParams` function can be restored and used to `paths` array.

**Comment by rtritto** [comment]
This logic can be restored:
```diff
  const paths: [path: string, exportName: string][] = [];

  for await (const filePath of files) {
  // ...
-    if (types) paths.push([fullPath.replace(directoryPath, ""), importName]);
+    paths.push([fullPath.replace(directoryPath, ""), importName]);
  }

+  if (failGlob && files.length === 0)
+    throw new Error(
+      `No matches found in ${directoryPath}. You can disable this error by setting the failGlob parameter to false in the options of autoload plugin`,
+    );
```

@kravetsone what do you think about?

**Comment by rtritto** [comment]
Because I changed the glob scan to async iteration with streams (https://bun.sh/docs/api/glob#quickstart) and the filepath list can't be collected.

**Comment by kravetsone** [comment]
> Because I changed the glob scan to async iteration with streams (https://bun.sh/docs/api/glob#quickstart) and the filepath list can't be collected.

It is possible to add `let isEmpty` and in for if it false set to true
And u will know if generator return zero results 
I guess maybe a better way exists but this way is okay too

**Comment by kravetsone** [comment]
> Changed to use glob with async iteration with streams.
> If needed, `sortByNestedParams` function can be restored and used to `paths` array (after `for async`).
> https://github.com/kravetsone/elysia-autoload/blob/a059f511e4f7e69e1c21ca075c08372bbede3a28/src/index.ts#L132

I add `sortByNestedParams` to prevent `some/[ok]` be higher than `some/ok`

Because path with params should be connected in last way

**Comment by rtritto** [comment]
> > Changed to use glob with async iteration with streams.
> > If needed, `sortByNestedParams` function can be restored and used to `paths` array (after `for async`).
> > https://github.com/kravetsone/elysia-autoload/blob/a059f511e4f7e69e1c21ca075c08372bbede3a28/src/index.ts#L132
> 
> I add `sortByNestedParams` to prevent `some/[ok]` be higher than `some/ok`
> 
> Because path with params should be connected in last way

Ok, I restored the previous logic.

**Comment by kravetsone** [comment]
is this PR ready for merge?

**Comment by kravetsone** [comment]
Do we really need esbuild?

I guess we can recommend `tsx` to execute TS on NodeJS

It is also recommended in NodeJS documentation and it has support for import(".ts")

**Comment by rtritto** [comment]
> is this PR ready for merge?

I don't know if we should add a message error when using NodeJS and missing `esbuild`.
Anyway README needs to be updated with NodeJS usage case (install `esbuild` when using `.ts` files etc).

> Do we really need esbuild?

NodeJS doesn't support `.ts` files. `esbuild` is an optional peer dependency.

> I guess we can recommend `tsx` to execute TS on NodeJS
>
> It is also recommended in NodeJS documentation and it has support for import(".ts")

`tsx` uses `esbuild` under to hood and `esbuild` is used widely (so it can be easily deduped and we have essentials dependencies).
If there is a pereferred (usefull) setting in `tsx`, we can copy it.

**Comment by kravetsone** [comment]
> > is this PR ready for merge?
> 
> I don't know if we should add a message error when using NodeJS and missing `esbuild`.
> Anyway README needs to be updated with NodeJS usage case (install `esbuild` when using `.ts` files etc).
> 
> Note: on merging this PR, I would use the squash (cleaner history) instead of the merge.
> 
> > Do we really need esbuild?
> 
> NodeJS doesn't support `.ts` files. `esbuild` is an optional peer dependency.
> 
> > I guess we can recommend `tsx` to execute TS on NodeJS
> >
> > It is also recommended in NodeJS documentation and it has support for import(".ts")
> 
> `tsx` uses `esbuild` under the hood and `esbuild` is used widely (so it can be easily deduped and we have essentials dependencies).
> If there is a pereferred (usefull) setting in `tsx`, we can copy it.

I mean that `tsx` is de-facto standard and it mentioned in NodeJS documentation 

So if some TypeScript executor isn't support `.ts` files it will be not our problem)
I guess no need to use esbuild directly in plugin
It's more about executor scope

**Comment by rtritto** [comment]
> I mean that `tsx` is de-facto standard and it mentioned in NodeJS documentation
>
> So if some TypeScript executor isn't support .ts files it will be not our problem)
I guess no need to use esbuild directly in plugin
It's more about executor scope

In the [doc](https://nodejs.org/api/typescript.html), `tsx` is used in scripts.
In our use case, we can use directly `esbuild` like `vite` and `vike` projects.
Another point where `tsx` (currently) uses `esbuild@~0.23.0` and latest `esbuild` version is `0.24.0`. Using directly `esbuild` directly as dev dependency, the user can choose which version to use (in case of problems or every kind of updates).

**Comment by kravetsone** [comment]
> > I mean that `tsx` is de-facto standard and it mentioned in NodeJS documentation
> >
> > So if some TypeScript executor isn't support .ts files it will be not our problem)
> I guess no need to use esbuild directly in plugin
> It's more about executor scope
> 
> In the [doc](https://nodejs.org/api/typescript.html), `tsx` is used only with scripts (shell).
> In our use case, we can use directly `esbuild` like `vite` and `vike` projects.
> Another point where `tsx` (currently) uses `esbuild@~0.23.0` and latest `esbuild` version is `0.24.0`. Using directly `esbuild` as dev dependency, the user can choose which version to use (in case of problems or every kind of updates).

Didn't understand what u mean by "we can use directly" What's we get with it?

Seems like elysia application will be bundled or executed by `tsx`

**Comment by rtritto** [comment]
> Didn't understand what u mean by "we can use directly" What's we get with it?

`esbuild` is a bundler and it's used to build and transpile.
`tsx` is used, in place of `node` command, to execute code (shell commands, package.json scripts etc) with a loader. Under the hood it uses `esbuild` to transpile and then execute.
With "directly" I mean that we can use the _build function_ of `esbuild` instead of `tsx` that uses the _build function_ of `esbuild`.

> Seems like elysia application will be bundled or executed by tsx

Elysia is bundled with `tsup` (an alternative to `pkgroll` and that uses `esbuild`) and then with Bun ([source](https://github.com/elysiajs/elysia/blob/main/build.ts)). It's executed by Bun ([Bun runtime with TypeScript](https://bun.sh/docs/runtime/typescript)).

---

Some differences: https://dev.to/andreasbergstrom/simplify-typescript-builds-with-esbuild-and-skip-tsctsx-2124

Some references:
- https://bun.sh/docs/bundler/vs-esbuild
- https://bun.sh/docs/api/transpiler

**Comment by kravetsone** [comment]
> > Не понял, что вы имеете в виду, говоря «мы можем использовать напрямую». Что мы получаем взамен?
> 
> `esbuild`является сборщиком и используется для сборки и транспиляции. `tsx`используется вместо `node`команды для выполнения кода (команд оболочки, скриптов package.json и т. д.) с помощью загрузчика. Под капотом он используется `esbuild`для транспиляции и последующего выполнения. Под «напрямую» я подразумеваю, что мы можем использовать функцию _сборки_`esbuild` вместо , `tsx`которая использует функцию _сборки_`esbuild` .
> 
> > Похоже, что приложение elysia будет объединено или запущено tsx
> 
> Elysia поставляется в комплекте с `tsup`(альтернатива `pkgroll`и , которая использует `esbuild`), а затем с Bun ( [источник](https://github.com/elysiajs/elysia/blob/main/build.ts) ). Он выполняется Bun ( [среда выполнения Bun с TypeScript](https://bun.sh/docs/runtime/typescript) ).
> 
> Некоторые отличия: https://dev.to/andreasbergstrom/simplify-typescript-builds-with-esbuild-and-skip-tsctsx-2124
> 
> Некоторые ссылки:
> 
> * https://bun.sh/docs/bundler/vs-esbuild
> * https://bun.sh/docs/api/transpiler

yeah `tsx` is executor 
`esbuild` is bundler

and classic user flow will be:

1. use tsx to execute typescript files (works with `elysia-autoload` because `import(".ts")` supported)
2. transpile it via bundler (works with `elysia-autoload` because files transpiled to `.js`)

So why we need to execute `esbuild` directly?

**Comment by rtritto** [comment]
When you start `vite` and `vike`, you don't use `tsx` because they use `esbuild` internally. At same way, `elysia-autoload` should use `esbuild`.
Use `tsx` when you need to start `.ts` (execute a file with no exports).
Use `esbuild` when you internally check the extension and you can select the default or named export(s) to execute or use.

**Comment by rtritto** [comment]
@kravetsone the error `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /<FILE>.ts`, with the dynamic `import` on Node.js for `.ts` and `.tsx` files, has a related issue with `Vite`: https://github.com/vitejs/vite/issues/5370

As probably Bun do, a loader needs to be used on entrypoint.

So, I did a commit to remove `esbuild`.

Imo we can always use `pathToFileURL` (same as #30):
```ts
const file = await import(pathToFileURL(fullPath).href)
```
instead of
```ts
let file;
if (typeof Bun === "undefined")
  ? await import(pathToFileURL(fullPath).href)
  : await import(fullPath)
```

What do you think about?

**Comment by rtritto** [comment]
My comment: https://github.com/vitejs/vite/issues/5370#issuecomment-2514998156

**Comment by kravetsone** [comment]
Thanks for the work! Love it

For final i guess we should not include any loaders to this library. 
We should talk to user about this.

Also `tsx` is a great solution and no problem will be caused by this. 
And `type stripping` in new Node.js versions will be fine!

**Pull request merged**
